apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-letr
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: cowpanda/alpine-node-pm2:latest
        workingDir: /code
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /code
          name: codenodejs
        command: ["/usr/local/bin/pm2", "start", "--no-daemon", "hostname.js"]
#        args: ["pm2", "start --no-daemon /code/hello1.js"]
      volumes:
       - name: codenodejs
         hostPath: 
          path: /code
          type: Directory
#      hostAliases:
#      - ip: 127.0.0.1
#        hostnames:
#        - "nodejs.hostname"


---
apiVersion: v1
kind: Service
metadata:
  namespace: test-letr
  name: nodejs-service
  labels:
    app: nodejs-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: nodejs

