apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-letr
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginxvolume
      volumes:
       - name: nginxvolume
         hostPath:
          path: /code/nginx
          type: Directory


---
apiVersion: v1
kind: Service
metadata:
  namespace: test-letr
  name: nginx-service
spec:
  selector:
    app: nginx

  type: NodePort
#  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30100



